package snmpdiscovery

import (
	"fmt"
	"net"
	"os"
	"regexp"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

var authNameRE = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_.-]*$`)

// InitAuth is one named credential block for auths.yml.
type InitAuth struct {
	Name          string
	Version       int
	Community     string
	Username      string
	Password      string
	PrivPassword  string
	SecurityLevel string
	AuthProtocol  string
	PrivProtocol  string
	ContextName   string
}

// InitGroup is one discovery group. Auths are names that must exist on the plan.
type InitGroup struct {
	Name          string
	CIDRs         []string
	Auths         []string
	Fingerprinter string
	Mode          string
	Port          uint16
	Ping          bool
	AllowLarge    bool
}

// InitPlan is the two files a first-time operator writes.
type InitPlan struct {
	Auths  []InitAuth
	Groups []InitGroup
}

// ValidateInitPlan checks names, CIDRs, and that every group auth exists on the plan.
func ValidateInitPlan(p InitPlan) error {
	if len(p.Auths) == 0 {
		return fmt.Errorf("init: at least one auth is required")
	}
	if len(p.Groups) == 0 {
		return fmt.Errorf("init: at least one group is required")
	}
	seenAuth := map[string]struct{}{}
	for i, a := range p.Auths {
		name := strings.TrimSpace(a.Name)
		if !authNameRE.MatchString(name) {
			return fmt.Errorf("init: auths[%d] name %q (use letters, digits, _ . -; start with a letter)", i, a.Name)
		}
		if _, ok := seenAuth[name]; ok {
			return fmt.Errorf("init: duplicate auth %q", name)
		}
		seenAuth[name] = struct{}{}
		switch a.Version {
		case 1, 2:
			if strings.TrimSpace(a.Community) == "" {
				return fmt.Errorf("init: auth %q needs a community", name)
			}
		case 3:
			if strings.TrimSpace(a.Username) == "" {
				return fmt.Errorf("init: auth %q needs a username", name)
			}
			level := strings.TrimSpace(a.SecurityLevel)
			if level == "" {
				level = "authPriv"
			}
			switch level {
			case "noAuthNoPriv":
			case "authNoPriv":
				if strings.TrimSpace(a.Password) == "" {
					return fmt.Errorf("init: auth %q authNoPriv needs an auth password", name)
				}
			case "authPriv":
				if strings.TrimSpace(a.Password) == "" || strings.TrimSpace(a.PrivPassword) == "" {
					return fmt.Errorf("init: auth %q authPriv needs auth and priv passwords", name)
				}
			default:
				return fmt.Errorf("init: auth %q security_level %q (want noAuthNoPriv, authNoPriv, authPriv)", name, level)
			}
		default:
			return fmt.Errorf("init: auth %q version %d (want 1, 2, or 3)", name, a.Version)
		}
	}
	seenGroup := map[string]struct{}{}
	for i, g := range p.Groups {
		name := strings.TrimSpace(g.Name)
		if name == "" {
			return fmt.Errorf("init: groups[%d] missing name", i)
		}
		if _, ok := seenGroup[name]; ok {
			return fmt.Errorf("init: duplicate group %q", name)
		}
		seenGroup[name] = struct{}{}
		if len(g.CIDRs) == 0 {
			return fmt.Errorf("init: group %q has no cidrs", name)
		}
		for _, c := range g.CIDRs {
			if err := validateInitCIDR(c, g.AllowLarge); err != nil {
				return fmt.Errorf("init: group %q: %w", name, err)
			}
		}
		if len(g.Auths) == 0 {
			return fmt.Errorf("init: group %q has no auths (pick names from the auth list)", name)
		}
		for _, an := range g.Auths {
			if _, ok := seenAuth[an]; !ok {
				return fmt.Errorf("init: group %q lists auth %q which is not in auths.yml", name, an)
			}
		}
		mode := strings.ToLower(strings.TrimSpace(g.Mode))
		if mode == "" {
			mode = modeSweep
		}
		switch mode {
		case modeSweep, modeCrawl, modeBoth:
		default:
			return fmt.Errorf("init: group %q mode %q (want sweep, crawl, or both)", name, g.Mode)
		}
	}
	return nil
}

func validateInitCIDR(raw string, allowLarge bool) error {
	s := strings.TrimSpace(raw)
	if s == "" {
		return fmt.Errorf("empty CIDR")
	}
	if !strings.Contains(s, "/") {
		if _, err := canonIP(s); err != nil {
			return err
		}
		return nil
	}
	_, ipnet, err := net.ParseCIDR(s)
	if err != nil {
		return fmt.Errorf("invalid CIDR %s", s)
	}
	ones, bits := ipnet.Mask.Size()
	hostBits := bits - ones
	if hostBits > maxSweepHostBits && !allowLarge {
		maxPrefix := bits - maxSweepHostBits
		return fmt.Errorf("CIDR %s is wider than /%d (~1024 hosts); set allow_large if you really want that", s, maxPrefix)
	}
	return nil
}

func yamlScalar(s string) string {
	b, err := yaml.Marshal(s)
	if err != nil {
		return strconv.Quote(s)
	}
	return strings.TrimSpace(string(b))
}

// RenderAuthsYAML writes an auths-only overlay (snmp_exporter shape).
func RenderAuthsYAML(auths []InitAuth) (string, error) {
	if len(auths) == 0 {
		return "", fmt.Errorf("init: no auths")
	}
	var b strings.Builder
	b.WriteString("# Generated by snmp-discovery init. Keep mode 0600. Do not commit.\n")
	b.WriteString("# Discovery lists these names only. Merge this map into the exporter --config.file.\n")
	b.WriteString("auths:\n")
	for _, a := range auths {
		b.WriteString("  " + a.Name + ":\n")
		b.WriteString(fmt.Sprintf("    version: %d\n", a.Version))
		if a.Version == 1 || a.Version == 2 {
			b.WriteString("    community: " + yamlScalar(a.Community) + "\n")
			continue
		}
		level := strings.TrimSpace(a.SecurityLevel)
		if level == "" {
			level = "authPriv"
		}
		b.WriteString("    security_level: " + yamlScalar(level) + "\n")
		b.WriteString("    username: " + yamlScalar(a.Username) + "\n")
		if a.Password != "" {
			b.WriteString("    password: " + yamlScalar(a.Password) + "\n")
		}
		if a.PrivPassword != "" {
			b.WriteString("    priv_password: " + yamlScalar(a.PrivPassword) + "\n")
		}
		authP := strings.TrimSpace(a.AuthProtocol)
		if authP == "" && level != "noAuthNoPriv" {
			authP = "SHA256"
		}
		if authP != "" {
			b.WriteString("    auth_protocol: " + yamlScalar(authP) + "\n")
		}
		privP := strings.TrimSpace(a.PrivProtocol)
		if privP == "" && level == "authPriv" {
			privP = "AES"
		}
		if privP != "" {
			b.WriteString("    priv_protocol: " + yamlScalar(privP) + "\n")
		}
		if c := strings.TrimSpace(a.ContextName); c != "" {
			b.WriteString("    context_name: " + yamlScalar(c) + "\n")
		}
	}
	return b.String(), nil
}

// RenderDiscoveryYAML writes groups that only name auths from the plan.
func RenderDiscoveryYAML(groups []InitGroup) (string, error) {
	if len(groups) == 0 {
		return "", fmt.Errorf("init: no groups")
	}
	var b strings.Builder
	b.WriteString("# Generated by snmp-discovery init. Auths are names from auths.yml.\n")
	b.WriteString("groups:\n")
	for _, g := range groups {
		mode := strings.ToLower(strings.TrimSpace(g.Mode))
		if mode == "" {
			mode = modeSweep
		}
		fp := strings.TrimSpace(g.Fingerprinter)
		if fp == "" {
			fp = "network"
		}
		port := g.Port
		if port == 0 {
			port = 161
		}
		b.WriteString("  - name: " + yamlScalar(g.Name) + "\n")
		b.WriteString("    cidrs:\n")
		for _, c := range g.CIDRs {
			b.WriteString("      - " + yamlScalar(c) + "\n")
		}
		b.WriteString("    auths:\n")
		for _, a := range g.Auths {
			b.WriteString("      - " + yamlScalar(a) + "\n")
		}
		b.WriteString("    fingerprinter: " + yamlScalar(fp) + "\n")
		b.WriteString("    mode: " + yamlScalar(mode) + "\n")
		b.WriteString("    ping: " + strconv.FormatBool(g.Ping) + "\n")
		b.WriteString(fmt.Sprintf("    port: %d\n", port))
		if g.AllowLarge {
			b.WriteString("    allow_large: true\n")
		}
	}
	b.WriteString("overrides: []\n")
	return b.String(), nil
}

// WriteInitFiles writes auths.yml (0600) and discovery.yml (0644).
func WriteInitFiles(authsPath, discoveryPath string, p InitPlan, overwrite bool) error {
	if err := ValidateInitPlan(p); err != nil {
		return err
	}
	ay, err := RenderAuthsYAML(p.Auths)
	if err != nil {
		return err
	}
	dy, err := RenderDiscoveryYAML(p.Groups)
	if err != nil {
		return err
	}
	if err := writeNewFile(authsPath, []byte(ay), 0o600, overwrite); err != nil {
		return err
	}
	if err := writeNewFile(discoveryPath, []byte(dy), 0o644, overwrite); err != nil {
		return err
	}
	return nil
}

func writeNewFile(path string, body []byte, mode os.FileMode, overwrite bool) error {
	if path == "" {
		return fmt.Errorf("init: empty path")
	}
	if _, err := os.Stat(path); err == nil && !overwrite {
		return fmt.Errorf("%s exists (pass --force to overwrite)", path)
	}
	if err := os.WriteFile(path, body, mode); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

// AuthNamesInFile returns the auths: map keys from a YAML overlay or snmp.yml.
func AuthNamesInFile(path string) (map[string]struct{}, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg snmpFile
	if err := yaml.Unmarshal(b, &cfg); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	out := map[string]struct{}{}
	for k := range cfg.Auths {
		out[k] = struct{}{}
	}
	return out, nil
}

// CheckAuthDiscovery ensures every discovery group auth exists in auths.yml
// and/or --snmp-config. At least one secret file is required.
func CheckAuthDiscovery(authsPath, discoveryPath, snmpConfigPath string) error {
	names := map[string]struct{}{}
	var sources []string
	if p := strings.TrimSpace(authsPath); p != "" {
		got, err := AuthNamesInFile(p)
		if err != nil {
			return err
		}
		for k := range got {
			names[k] = struct{}{}
		}
		sources = append(sources, p)
	}
	if p := strings.TrimSpace(snmpConfigPath); p != "" {
		got, err := AuthNamesInFile(p)
		if err != nil {
			return err
		}
		for k := range got {
			names[k] = struct{}{}
		}
		sources = append(sources, p)
	}
	if len(names) == 0 {
		return fmt.Errorf("init --check: no auths in %s", strings.Join(append([]string{}, sources...), " or "))
	}
	disc, err := LoadDiscoveryFile(discoveryPath)
	if err != nil {
		return err
	}
	var missing []string
	seen := map[string]struct{}{}
	for _, g := range disc.Groups {
		for _, a := range g.Auths {
			if _, ok := names[a]; ok {
				continue
			}
			if _, dup := seen[a]; dup {
				continue
			}
			seen[a] = struct{}{}
			missing = append(missing, a)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("init --check: discovery names %v are not in %s", missing, strings.Join(sources, " + "))
	}
	return nil
}

// ParseAuthV2Flag accepts "public_v2=public" or "name=public_v2,community=public".
func ParseAuthV2Flag(s string, version int) (InitAuth, error) {
	if version != 1 && version != 2 {
		return InitAuth{}, fmt.Errorf("version %d", version)
	}
	s = strings.TrimSpace(s)
	a := InitAuth{Version: version}
	if strings.Contains(s, ",") || strings.Contains(s, "name=") || strings.Contains(s, "community=") {
		kv := splitFlagKV(s)
		a.Name = kv["name"]
		a.Community = kv["community"]
	} else {
		name, comm, ok := strings.Cut(s, "=")
		if !ok {
			return InitAuth{}, fmt.Errorf("want name=community, got %q", s)
		}
		a.Name = strings.TrimSpace(name)
		a.Community = comm
	}
	if a.Name == "" || a.Community == "" {
		return InitAuth{}, fmt.Errorf("auth-v%d %q needs name and community", version, s)
	}
	return a, nil
}

// ParseAuthV3Flag accepts "dc_v3,level=authPriv,user=netops,auth=secret,priv=secret".
func ParseAuthV3Flag(s string) (InitAuth, error) {
	kv := splitFlagKV(s)
	a := InitAuth{
		Name:          firstNonEmpty(kv["name"], kv["_name"]),
		Version:       3,
		SecurityLevel: firstNonEmpty(kv["level"], kv["security_level"], "authPriv"),
		Username:      firstNonEmpty(kv["user"], kv["username"]),
		Password:      firstNonEmpty(kv["auth"], kv["password"]),
		PrivPassword:  firstNonEmpty(kv["priv"], kv["priv_password"]),
		AuthProtocol:  firstNonEmpty(kv["auth-proto"], kv["auth_protocol"], "SHA256"),
		PrivProtocol:  firstNonEmpty(kv["priv-proto"], kv["priv_protocol"], "AES"),
		ContextName:   firstNonEmpty(kv["context"], kv["context_name"]),
	}
	if a.Name == "" {
		return InitAuth{}, fmt.Errorf("auth-v3 %q needs a name (name=… or leading token)", s)
	}
	return a, nil
}

// ParseGroupFlag accepts "lab,cidrs=10.0.0.0/24,auths=public_v2".
// Multiple CIDRs / auths: cidrs=a;b  auths=x;y
func ParseGroupFlag(s string) (InitGroup, error) {
	kv := splitFlagKV(s)
	g := InitGroup{
		Name:          firstNonEmpty(kv["name"], kv["_name"]),
		Fingerprinter: firstNonEmpty(kv["fingerprinter"], "network"),
		Mode:          firstNonEmpty(kv["mode"], modeSweep),
		Ping:          true,
		Port:          161,
	}
	if v := kv["cidrs"]; v != "" {
		g.CIDRs = splitSemi(v)
	}
	if v := kv["auths"]; v != "" {
		g.Auths = splitSemi(v)
	}
	if v := kv["port"]; v != "" {
		n, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return InitGroup{}, fmt.Errorf("group port: %w", err)
		}
		g.Port = uint16(n)
	}
	if v := kv["ping"]; v != "" {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return InitGroup{}, fmt.Errorf("group ping: %w", err)
		}
		g.Ping = p
	}
	if v := kv["allow_large"]; v != "" {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return InitGroup{}, fmt.Errorf("group allow_large: %w", err)
		}
		g.AllowLarge = p
	}
	if g.Name == "" || len(g.CIDRs) == 0 || len(g.Auths) == 0 {
		return InitGroup{}, fmt.Errorf("group %q needs name, cidrs, and auths", s)
	}
	return g, nil
}

func splitSemi(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ";") {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func firstNonEmpty(ss ...string) string {
	for _, s := range ss {
		if strings.TrimSpace(s) != "" {
			return strings.TrimSpace(s)
		}
	}
	return ""
}

// splitFlagKV parses "name,cidrs=10.0.0.0/24,auths=public_v2".
// A leading token without "=" becomes _name (and name= if unset).
func splitFlagKV(s string) map[string]string {
	out := map[string]string{}
	for i, part := range strings.Split(s, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		k, v, ok := strings.Cut(part, "=")
		if !ok {
			if i == 0 {
				out["_name"] = part
				out["name"] = part
			}
			continue
		}
		out[strings.TrimSpace(k)] = v
	}
	return out
}
