#!/usr/bin/env python3
"""Look up OBJECT-TYPE SYNTAX for profile OIDs via public OID pages.

Does not ship or clone a MIB tree. Writes snmp/oid-syntax.yaml for convert.py.

Primary:  https://oid-base.com/get/<oid>   (ASN.1 DESCRIPTION with SYNTAX)
Fallback: https://oidref.com/<oid>
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "snmp" / "oid-syntax.yaml"
DEFAULT_CACHE = Path.home() / ".cache" / "snmp-sd-oid-syntax"
DEFAULT_PROFILES = ROOT / "snmp" / "profiles"

OID_LINE = re.compile(r"""(?i)\bOID:\s*['"]?\.?([0-9]+(?:\.[0-9]+)+)""")
SYNTAX_RE = re.compile(r"\bSYNTAX\s+([A-Za-z][A-Za-z0-9-]*)", re.I)
NAME_RE = re.compile(r"\b([A-Za-z][A-Za-z0-9-]*)\s+OBJECT-TYPE\b")

UA = "snmp-sd-profile-convert/lookup-oid-syntax (+https://github.com/Mesverrum/snmp-sd)"


def exporter_type(syntax: str) -> str:
    s = syntax.upper().replace(" ", "").replace("-", "")
    if "COUNTER" in s:
        return "counter"
    return "gauge"


def normalize_oid(oid: str) -> str:
    oid = oid.strip().lstrip(".")
    if oid.endswith(".0") and oid.count(".") >= 6:
        oid = oid[:-2]
    return oid


def collect_oids(root: Path) -> list[str]:
    seen: set[str] = set()
    for path in root.rglob("*"):
        if path.suffix.lower() not in {".yml", ".yaml"}:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for m in OID_LINE.finditer(text):
            seen.add(normalize_oid(m.group(1)))
    return sorted(seen)


def parse_syntax(body: str) -> tuple[str, str]:
    """Return (object_name, syntax) or ('', '')."""
    syn_m = SYNTAX_RE.search(body)
    if not syn_m:
        return "", ""
    name_m = NAME_RE.search(body)
    return (name_m.group(1) if name_m else ""), syn_m.group(1)


def http_get(url: str, timeout: float) -> tuple[int, str]:
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "text/html"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read()
            return int(resp.status), raw.decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
        return int(exc.code), body
    except urllib.error.URLError:
        return 0, ""


def lookup_one(oid: str, timeout: float) -> dict[str, str] | None:
    sources = (
        ("oid-base", f"https://oid-base.com/get/{oid}"),
        ("oidref", f"https://oidref.com/{oid}"),
    )
    for source, url in sources:
        status, body = http_get(url, timeout)
        if status != 200 or not body:
            continue
        name, syntax = parse_syntax(body)
        if not syntax:
            continue
        return {
            "name": name,
            "syntax": syntax,
            "type": exporter_type(syntax),
            "source": source,
        }
    return None


def load_existing(path: Path) -> dict[str, dict]:
    if not path.is_file() or yaml is None:
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    raw = data.get("oids") or {}
    out: dict[str, dict] = {}
    for key, val in raw.items():
        if isinstance(val, dict) and val.get("type") in {"counter", "gauge"}:
            out[str(key).lstrip(".")] = val
    return out


def dump_doc(path: Path, oids: dict[str, dict], wanted: int, missing: list[str]) -> None:
    counters = sum(1 for v in oids.values() if v.get("type") == "counter")
    doc = {
        "description": (
            "OBJECT-TYPE SYNTAX → snmp_exporter metric type. "
            "Generated by tools/snmp-profile-convert/lookup-oid-syntax.py "
            "from public OID pages (oid-base.com, oidref.com). Not a MIB library."
        ),
        "oids_wanted": wanted,
        "oids_resolved": len(oids),
        "oids_missing": len(missing),
        "counter": counters,
        "gauge": len(oids) - counters,
        "oids": oids,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    if yaml is None:
        path.write_text(json.dumps(doc, indent=2, sort_keys=False) + "\n", encoding="utf-8")
        return
    path.write_text(
        yaml.safe_dump(doc, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    if missing:
        path.with_suffix(path.suffix + ".missing").write_text(
            "\n".join(missing) + "\n", encoding="utf-8"
        )


def cache_get(cache: Path, oid: str) -> dict[str, str] | None:
    p = cache / f"{oid}.json"
    if not p.is_file():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if data.get("miss"):
        return None
    if data.get("type") in {"counter", "gauge"} and data.get("syntax"):
        return data
    return None


def cache_put(cache: Path, oid: str, hit: dict[str, str] | None) -> None:
    cache.mkdir(parents=True, exist_ok=True)
    p = cache / f"{oid}.json"
    payload = {"miss": True} if hit is None else hit
    p.write_text(json.dumps(payload), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--profiles", type=Path, default=DEFAULT_PROFILES)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--cache", type=Path, default=DEFAULT_CACHE)
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--timeout", type=float, default=20.0)
    ap.add_argument("--limit", type=int, default=0, help="Look up only the first N unresolved OIDs")
    ap.add_argument("--oid", action="append", default=[], help="Look up these OIDs only (repeatable)")
    ap.add_argument("--refresh", action="store_true", help="Ignore cache + existing yaml")
    args = ap.parse_args()

    if args.oid:
        wanted = [normalize_oid(o) for o in args.oid]
    else:
        wanted = collect_oids(args.profiles)
    if not wanted:
        print(f"ERROR: no OIDs in {args.profiles}", file=sys.stderr)
        return 1

    existing = {} if args.refresh else load_existing(args.out)
    todo = [o for o in wanted if o not in existing]
    if args.limit > 0:
        todo = todo[: args.limit]

    print(
        f"oids wanted={len(wanted)} already={len(existing)} todo={len(todo)} "
        f"workers={args.workers} cache={args.cache}",
        flush=True,
    )

    resolved = dict(existing)
    missing: list[str] = []
    done = 0
    t0 = time.time()

    def work(oid: str) -> tuple[str, dict[str, str] | None]:
        if not args.refresh:
            cached = cache_get(args.cache, oid)
            if cached:
                return oid, cached
        hit = lookup_one(oid, args.timeout)
        cache_put(args.cache, oid, hit)
        return oid, hit

    if todo:
        with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
            futs = [pool.submit(work, oid) for oid in todo]
            for fut in as_completed(futs):
                oid, hit = fut.result()
                done += 1
                if hit:
                    resolved[oid] = {
                        k: hit[k]
                        for k in ("name", "syntax", "type", "source")
                        if k in hit and hit[k]
                    }
                else:
                    missing.append(oid)
                if done % 25 == 0 or done == len(todo):
                    rate = done / max(time.time() - t0, 0.001)
                    print(
                        f"  {done}/{len(todo)} resolved={len(resolved)} "
                        f"miss={len(missing)} {rate:.1f}/s",
                        flush=True,
                    )
                    dump_doc(args.out, resolved, len(wanted), missing)

    # Recompute missing against the full wanted set (refresh / resume).
    missing = [o for o in wanted if o not in resolved]
    dump_doc(args.out, resolved, len(wanted), missing)
    print(
        f"wrote {args.out} resolved={len(resolved)}/{len(wanted)} "
        f"missing={len(missing)}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
